### ISSUE TITLE
debase 0.2.3 fails to compile with ruby 2.6.0 and debase-ruby_core_source v0.10.4

### ISSUE THREAD

**Issue by rockorequin** [os97673/debase-ruby_core_source#12]
debase v0.2.3.beta2 fails to build for ruby 2.6.0 saying that FALSE isn't defined in breakpoint.c, and I think the issue is in debase-ruby_core_source v0.10.4: the file vm_insnhelper.h doesn't include regenc.h, which is needed to define FALSE. There are more details at https://github.com/denofevil/debase/issues/67#issuecomment-451353184.

**Comment by os97673** [comment]
@valich could you please help with this.  I do not have environment ready to test changes in this area :(

**Comment by rubydev** [comment]
@os97673 I included `regenc.h` to `vm_insnhelper.h` as @rockorequin suggested and it works, so I created PR https://github.com/os97673/debase-ruby_core_source/pull/13
