### ISSUE TITLE
v0.10.13 release - is this gem safe or hijacked?

### ISSUE THREAD

**Issue by ShockwaveNN** [os97673/debase-ruby_core_source#25]
Hi, I saw that last commits at this repo was made in [2019 year](https://github.com/os97673/debase-ruby_core_source/commit/ed1ad985416af79669559990fec2d3dc64500754) -  at times of release gem version v0.10.9

But according to [rubygems](https://rubygems.org/gems/debase-ruby_core_source/versions/0.10.13) there was 4 releases since dec of 2019

And last release was made today, on 22 nov of 2021

Is this gem hijacked? Someone making releases without actual commits and changes in code of this repo?
Or is this just a complicated release process and maybe some note should be added to README?

**Comment by os97673** [comment]
I’ve delegated maintenance of the gem to RubyMine team. The latest version of the gem has been released by https://rubygems.org/profiles/hurricup so I presume they just have not updated the repo. 
@valich & @denofevil  could you please confirm that the releases are valid. And could you please consider either update the repo or change link to the correct repo for the gem.

**Comment by hurricup** [comment]
Please, see https://github.com/ruby-debug/debase-ruby_core_source
I've gathered all debugger-related projects in  https://github.com/ruby-debug/ and maintaining there. No worries.

**Comment by ShockwaveNN** [comment]
@hurricup in that case I think gemspec should be updated so rubygems page will direct to correct repo

**Comment by hurricup** [comment]
Done, thank you. Missed that.

**Comment by ShockwaveNN** [comment]
Thank you!
I think it's better to relase new version of gem, so it will display correct info on rubygems page and we can close all question regarding owners of this gem

But it's up to you, if you really want make a release
