### ISSUE TITLE
Rubygems not updated after 0.9.9

### ISSUE THREAD

**Issue by gerrywastaken** [os97673/debase-ruby_core_source#6]
Hi maybe I'm missing something but it seems no version after 0.9.9 has been pushed to rubygems.org:

https://rubygems.org/gems/debase-ruby_core_source/versions

**Comment by os97673** [comment]
Why do you need a new version?

**Comment by gerrywastaken** [comment]
Actually, you are correct, I do not. I just took another look at 0.9.9 and it contains support for the version I need. Sorry about that.

**Comment by os97673** [comment]
No problem, I'm happy I have nothing to do ;)
